### ISSUE TITLE
Document how to extend pywebpack (e.g. entry points)

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/pywebpack#15]
Example: https://github.com/getredash/redash/issues/2565

**Comment by michaeltoohig** [comment]
The documents as they stand I find are a bit more vague than the documents available for the flask extension. Perhaps since using this the flask extension has "one way to do it". But when reading the docs I'm tripped up by the non-specific filenames and no context of folder structure like in the flask example. Just for reference I'm looking at the multi entry point examples.
