### ISSUE TITLE
Tests fail if webpack not available

### ISSUE THREAD

**Issue by pferreir** [inveniosoftware/pywebpack#9]
I'm not sure what should be done in this case. Maybe the test packages themselves could have webpack as a dependency and we would run it from `node_modules/.bin/...`?
Or we can install webpack in a tmp dir and use that one?
Or otherwise we just abort the tests if the `webpack` command is not available?

**Comment by lnielsen** [comment]
Yeah, it would be better if it was available. I assumed webpack was installed originally just in order to speed up tests. E.g. also the package.json don't really have dependencies because then the tests take quite long time.

I'm fine with either aborting, or install webpack  somehow if it's not available.

**Comment by ntarocco** [comment]
Would it be enough to add a check and if not installed a `npm install webpack && npm install webpack-cli` in `run-tests.sh`?
Or you should happen when you run `pytest`/`python setup.py test` directly?
